### ISSUE TITLE
OSError: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by ChristianMichelsen** [Dragon2fly/logger_tt#2]
Hi and thanks for a great library! 

I have a problem where I want to run separate jobs, each using logger_tt. When I do that, I run into the following error:

```python
OSError: [Errno 48] Address already in use
```
How do I specify to use another address or port? 

My setup is to run:

```python
from logger_tt import setup_logging, logger
from datetime import datetime

now = datetime.now()
now_str = now.strftime("%Y-%m-%d__%H-%M")
log_path = f"logs/log__{now_str}.log"

setup_logging(
    config_path=here_my_config_path,
    log_path=log_path,
)
```

with the following config file:

```yaml
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "[%(asctime)s] | %(name)s:%(lineno)d | %(levelname)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  brief:
    format: "[%(asctime)s] | %(levelname)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: brief
    stream: ext://sys.stdout

  error_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/log.txt
    backupCount: 15
    encoding: utf8
    when: midnight

loggers:
  urllib3:
    level: WARNING
    handlers: [console, error_file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console, error_file_handler]

logger_tt:
  suppress: ["exchangelib", "numba", "matplotlib", "absl"]
  suppress_level_below: "WARNING"
  capture_print: False
  strict: False
  guess_level: False
  full_context: 0
  use_multiprocessing: True
  limit_line_length: 1000
  analyze_raise_statement: False
  default_logger_formats:
    normal: ["%(name)s", "%(filename)s"]
    thread: ["%(message)s", "%(threadName)s %(message)s"]
    multiprocess: ["%(message)s", "%(processName)s | %(message)s"]
    both: ["%(message)s", "%(processName)s %(threadName)s %(message)s"]
```
